Luck_Unlucky = {
"The fool upright": [0],
"The magician upright": [1],
"High priestess upright": [1],
"Empress upright": [1],
"Emperor upright": [-1],
"Hierophant upright": [1],
"The lovers upright": [1],
"The chariot upright": [1],
"Justice upright": [1],
"The hermit upright": [0],
"Wheel of fortune upright": [0],
"Strength upright": [0],
"Hanged man upright": [-1],
"Death upright": [-1],
"Temperance upright": [1],
"The devil upright": [-1],
"The tower upright": [-1],
"The star upright": [1],
"The moon upright": [0],
"The sun upright": [1],
"Judgement upright": [1],
"The world upright": [1],
"The fool reversed": [0],
"The magician reversed": [-1],
"High priestess reversed": [-1],
"Empress reversed": [-1],
"Emperor reversed": [1],
"Hierophant reversed": [-1],
"The lovers reversed": [-1],
"The chariot reversed": [-1],
"Justice reversed": [-1],
"The hermit reversed": [0],
"Wheel of fortune reversed": [-1],
"Strength reversed": [0],
"Hanged man reversed": [-1],
"Death reversed": [1],
"Temperance reversed": [-1],
"The devil reversed": [-1],
"The tower reversed": [-1],
"The star reversed": [-1],
"The moon reversed": [0],
"The sun reversed": [-1],
"Judgement reversed": [-1],
"The world reversed": [-1]}
